 <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\AIT.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
   
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\DetectionClass.txt" />
    <None Remove="Assets\family.onnx" />
    <None Remove="Assets\family.yaml" />
    <None Remove="Assets\First.png" />
    <None Remove="Assets\MouseOff_LightDetect.onnx" />
    <None Remove="Assets\MouseOff_LightDetect.yaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\MouseOff_LightDetect.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MouseOff_LightDetect.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AIT.ico" />
  </ItemGroup>
  <!-- ========== 大恒相机 dll 引用 ========== -->
  <ItemGroup>
    <Reference Include="GxIAPINET">
      <HintPath>Libs\Daheng\GxIAPINET.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Libs\Daheng\GxIAPINET.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <!-- ====================================== -->
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MES_WPF.Core\MES_WPF.Core.csproj" />
    <ProjectReference Include="..\MES_WPF.Data\MES_WPF.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Icons\" />
    <Folder Include="ViewModels\ProductionManagement\" />
    <Folder Include="setup\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\First.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ProductionManagement\LabelInversionManualView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>